stages:
  - build
  - test
  - deploy

build_oscap:
  script:
    # - ansible-playbook playbooks/dependencies/main.yml
    # - chmod +x ./scripts/install-ssg.sh && ./scripts/install-ssg.sh
    - apt-get update
    - apt-get install -y curl bzip2 cmake python3-pip libxml2-utils ninja-build xsltproc # libopenscap8
    - pip install jinja2 pyyaml pytest pytest-cov json2html yamlpath mypy openpyxl pandas cmakelint sphinx sphinxcontrib-jinjadomain

    # Download SCAP Security Guide source code
    - ssg_version=$(curl --silent "https://api.github.com/repos/ComplianceAsCode/content/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
    - ssg_url="https://github.com/ComplianceAsCode/content/releases/download/v$ssg_version/scap-security-guide-$ssg_version.tar.bz2"
    - curl -so /tmp/scap-security-guide-$ssg_version.tar.bz2 -L "$ssg_url"
    - tar -xjf /tmp/scap-security-guide-$ssg_version.tar.bz2 -C /tmp

    # Build SCAP Security Guide
    - mkdir -p /tmp/scap-security-guide-$ssg_version/build
    - cmake -S /tmp/scap-security-guide-$ssg_version -B /tmp/scap-security-guide-$ssg_version/build
    - make install

    # Build oscap debian package
    # - make -C /tmp/scap-security-guide-$ssg_version/build -j4 debian11
    # - ls -la /tmp/scap-security-guide-$ssg_version/build
