- name: Install dependencies
  become: true
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - libopenscap8
    - libxml2-utils
    - ninja-build
    - xsltproc
