variables:
  GIT_DEPTH: 10
  GIT_SSL_NO_VERIFY: 1

stages:
  - build_oscap
  - test_oscap
  - deploy_oscap
  - build_ssg
  - deploy_ssg
  - scan

default:
  image:
    name: debian:11
    pull_policy: if-not-present
  tags:
    - docker

include:
  - local: build_dependencies/oscap.yml
  - local: build_dependencies/ssg.yml

run-security-scan:
  stage: scan
  script:
    - echo "Run security scan"
# run-security-scan:
#   stage: scan
#   # tags:
#   #   - shell
#   before_script:
#     - mkdir -p ~/.ssh
#     - cp -f "$SSH_PRIVATE_KEY" ~/.ssh/id_rsa
#     - chmod 400 ~/.ssh/id_rsa
#     # - rm -f ~/.ssh/known_hosts
#   needs: ["trigger_oscap"]
#   script:
#     - ansible-playbook playbooks/security-scan/main.yml
#   artifacts:
#     paths:
#       - reports
# after_script:
#   - rm ~/.ssh/id_rsa
