update-dependencies:
  tags:
    - docker
  script:
    - ansible-playbook playbooks/dependencies/main.yml

run-security-scan:
  tags:
    - shell
  before_script:
    - mkdir -p ~/.ssh
    - cp -f "$SSH_PRIVATE_KEY" ~/.ssh/id_rsa
    - chmod 400 ~/.ssh/id_rsa
    - rm -f ~/.ssh/known_hosts
  script:
    - ansible-playbook playbooks/security-scan/main.yml
  artifacts:
    paths:
      - reports
  after_script:
    - rm ~/.ssh/id_rsa
