- name: Install OpenSCAP dependencies
  become: true
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - cmake
    - libdbus-1-dev
    - libdbus-glib-1-dev
    - libcurl4-openssl-dev
    - libgcrypt20-dev
    - libselinux1-dev
    - libxslt1-dev
    - libgconf2-dev
    - libacl1-dev
    - libblkid-dev
    - libcap-dev
    - libxml2-dev
    - libldap2-dev
    - libpcre3-dev
    - python3-dev
    - swig
    - libxml-parser-perl
    - libxml-xpath-perl
    - libperl-dev
    - libbz2-dev
    - librpm-dev
    - g++
    - libapt-pkg-dev
    - libyaml-dev
    - libxmlsec1-dev
    - libxmlsec1-openssl
    - git

- name: Download OpenSCAP sources
  get_url:
    url: "{{ openscap_url }}"
    dest: "{{ openscap_install_dir }}.tar.gz"
    mode: 0644

- name: Extract OpenSCAP sources
  unarchive:
    src: "{{ openscap_install_dir }}.tar.gz"
    dest: "{{ openscap_install_dir }}/.."
    remote_src: yes

- name: Create OpenSCAP build directory
  file:
    path: "{{ openscap_install_dir }}/build"
    state: directory

- name: Build OpenSCAP
  become: true
  shell: cmake -DCMAKE_INSTALL_PREFIX=/usr ../ && make && make install
  args:
    chdir: "{{ openscap_install_dir }}/build"

- name: Remote scan
  shell: oscap-ssh --sudo vagrant@10.0.0.11 22 xccdf eval --datastream-id scap_org.open-scap_datastream_from_xccdf_ssg-debian11-xccdf.xml --xccdf-id scap_org.open-scap_cref_ssg-debian11-xccdf.xml --profile xccdf_org.ssgproject.content_profile_anssi_np_nt28_average --oval-results --results /tmp/xccdf-results.xml --results-arf /tmp/arf.xml --report /tmp/report.html /usr/local/share/xml/scap/ssg/content/ssg-debian11-ds.xml