stages:
  - build
  - test
  - deploy

default:
  image:
    name: debian:11
    pull_policy: if-not-present
  tags:
    - docker

variables:
  openscap_version: "1.3.7"

build_oscap:
  stage: build
  script:
    - pwd
    - ls -la
    - 'echo "OpenSCAP version: ${openscap_version}" >> oscap.txt'
    - openscap_version="1.3.8"
    - 'echo "OpenSCAP version: ${openscap_version}" >> oscap.txt'
  artifacts:
    paths:
      - oscap.txt
      # - oscap_${openscap_version}.deb
test_oscap:
  stage: test
  needs: ["build_oscap"]
  script:
    - cat oscap.txt
#     - apt update
#     - apt install ./oscap_${openscap_version}.deb
#     - oscap --version
