stages:
  - build
  - test
  - deploy

default:
  image:
    name: debian:11
    pull_policy: if-not-present
  tags:
    - docker

build_oscap:
  stage: build
  script:
    - pwd
    - ls -la
    - chmod +x build_dependencies/oscap.sh
    - build_dependencies/oscap.sh
  artifacts:
    paths:
      - oscap_${openscap_version}.deb
test_oscap:
  stage: test
  needs: ["build_oscap"]
  script:
    - apt update
    - apt install ./oscap_${openscap_version}.deb
    - oscap --version
