stages:
  - build
  - test
  - deploy

default:
  image: debian:11
  tags:
    - docker

build_oscap:
  stage: build
  script:
    - ./test.sh
  artifacts:
    paths:
      - oscap_${openscap_version}.deb

test_oscap:
  stage: test
  needs: ["build_oscap"]
  shell:
    - apt update
    - apt install ./oscap_${openscap_version}.deb
    - oscap --version
