stages:
  - build
  - test
  - deploy

build_oscap:
  stage: build
  script:
    - apt-get update
    - apt-get install -y curl bzip2 cmake python3-pip libxml2-utils ninja-build xsltproc # libopenscap8

    # Download Openscap source code
    - openscap_version=$(curl --silent "https://api.github.com/repos/OpenSCAP/openscap/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
    - openscap_url="https://github.com/OpenSCAP/openscap/releases/download/${openscap_version}/openscap-${openscap_version}.tar.gz"
    - curl -so /tmp/openscap-${openscap_version}.tar.gz -L "$openscap_url"
    - tar -xzpf /tmp/openscap-${openscap_version}.tar.gz -C /tmp

    # Install Openscap dependencies
    - apt-get install -y cmake libdbus-1-dev libdbus-glib-1-dev libcurl4-openssl-dev \
    - libgcrypt20-dev libselinux1-dev libxslt1-dev libgconf2-dev libacl1-dev libblkid-dev \
    - libcap-dev libxml2-dev libldap2-dev libpcre3-dev python3-dev swig libxml-parser-perl \
    - libxml-xpath-perl libperl-dev libbz2-dev librpm-dev g++ libapt-pkg-dev libyaml-dev \
    - libxmlsec1-dev libxmlsec1-openssl

    # Build Openscap
    - mkdir -p /tmp/openscap-${openscap_version}/build
    - cd /tmp/openscap-${openscap_version}/build
    - cmake -DCMAKE_INSTALL_PREFIX=/usr ../
    - make
    - make install

test_oscap:
  stage: test
  script:
    - oscap --version
