stages:
  - build
  - test
  - deploy

default:
  image:
    name: debian:11
    pull_policy: if-not-present
  tags:
    - docker

variables:
  openscap_version: ""

build_oscap:
  stage: build
  script:
    - apt update
    - apt install curl
    - openscap_version=$(curl --silent "https://api.github.com/repos/OpenSCAP/openscap/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
    - echo $openscap_version
#   artifacts:
#     paths:
#       - oscap.txt
#       # - oscap_${openscap_version}.deb
# test_oscap:
#   stage: test
#   needs: ["build_oscap"]
#   script:
#     - cat oscap.txt
#     - apt update
#     - apt install ./oscap_${openscap_version}.deb
#     - oscap --version
