stages:
  - build
  - test
  - deploy

default:
  image:
    name: debian:11
    pull_policy: if-not-present
  tags:
    - docker

variables:
  openscap_version: ""
  rebuild_oscap: "false"

build_oscap:
  stage: build
  script:
    - apt update
    - apt install -y curl
    - openscap_version=$(curl --silent "https://api.github.com/repos/OpenSCAP/openscap/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
    - current_oscap_version="1.3.7"
    - 'if [ "$openscap_version" == "$current_oscap_version" ]; then echo "No new version of OpenSCAP is available: $openscap_version"; exit 0; fi'
    - 'echo "New version of OpenSCAP is available: $openscap_version"''
#   artifacts:
#     paths:
#       - oscap.txt
#       # - oscap_${openscap_version}.deb
# test_oscap:
#   stage: test
#   needs: ["build_oscap"]
#   script:
#     - cat oscap.txt
#     - apt update
#     - apt install ./oscap_${openscap_version}.deb
#     - oscap --version
